# Generated by Django 2.2.11 on 2020-03-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='last_updated',
        ),
    ]
