# Generated by Django 2.2.11 on 2020-03-25 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_station_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
