# Generated by Django 2.2.4 on 2020-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('num_bikes_available', models.IntegerField()),
                ('num_docks_available', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
