# Generated by Django 2.2.4 on 2020-04-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='num_bikes_disabled',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='last_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
