# Generated by Django 2.2.4 on 2020-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200409_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_reported',
            field=models.DateTimeField(),
        ),
    ]
